name: Build

on:
  push:
    branches:
      - build_workflow
    paths:
      - 'manifest.json'
      - 'templates/**'
      - '.github/workflows/**'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: |
        JSON=$(cat ./manifest.json | jq [.[][]])
        JSON="${JSON//'%'/'%25'}"
        echo $JSON
        JSON="{\"include\":$JSON}"
        echo $JSON
        echo "-----------------------"
        echo "::set-output name=matrix::{\"include\":[ { \"directory\": \"templates\/java8\/cookiecutter-aws-sam-hello-powertools-java-gradle\", \"displayName\": \"Hello World Example with Lambda Powertools: Gradle\", \"dependencyManager\": \"gradle\", \"appTemplate\": \"powertools-hello-world\", \"javaVersion\": \"1.8\" }, { \"directory\": \"templates\/java8\/cookiecutter-aws-sam-hello-powertools-java-maven\", \"displayName\": \"Hello World Example with Lambda Powertools: Maven\", \"dependencyManager\": \"maven\", \"appTemplate\": \"powertools-hello-world\", \"javaVersion\": \"1.8\" }, { \"directory\": \"templates\/java8.al2\/cookiecutter-aws-sam-hello-powertools-java-gradle\", \"displayName\": \"Hello World Example with Lambda Powertools: Gradle\", \"dependencyManager\": \"gradle\", \"appTemplate\": \"powertools-hello-world\", \"javaVersion\": \"1.8\" }, { \"directory\": \"templates\/java8.al2\/cookiecutter-aws-sam-hello-powertools-java-maven\", \"displayName\": \"Hello World Example with Lambda Powertools: Maven\", \"dependencyManager\": \"maven\", \"appTemplate\": \"powertools-hello-world\", \"javaVersion\": \"1.8\" }, { \"directory\": \"templates\/java11\/cookiecutter-aws-sam-hello-powertools-java-gradle\", \"displayName\": \"Hello World Example with Lambda Powertools: Gradle\", \"dependencyManager\": \"gradle\", \"appTemplate\": \"powertools-hello-world\", \"javaVersion\": \"11\" }, { \"directory\": \"templates\/java11\/cookiecutter-aws-sam-hello-powertools-java-maven\", \"displayName\": \"Hello World Example with Lambda Powertools: Maven\", \"dependencyManager\": \"maven\", \"appTemplate\": \"powertools-hello-world\", \"javaVersion\": \"11\" } ]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          echo "${{ matrix.javaVersion }}"
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.include.javaVersion }}
      - name: Build with Maven
        if: ${{ matrix.include.dependencyManager == 'maven' }}
        run: mvn -B package --file ${{ matrix.include.directory }}/{{ cookiecutter.project_slug }}/HelloWorldFunction/pom.xml
      - name: Build with Gradle
        if: ${{ matrix.include.dependencyManager == 'gradle' }}
        run: ./${{ matrix.include.directory }}/{{ cookiecutter.project_slug }}/HelloWorldFunction/gradlew build
