name: Build

on:
  push:
    branches:
      - build_workflow
    paths:
      - 'manifest.json'
      - 'templates/**'
      - '.github/workflows/**'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        JSON=$(cat ./manifest.json | jq [.[][]])
        echo "::set-output name=matrix::{\"include\":${JSON//'%'/'%25'}}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.include.javaVersion }}
      - name: Build with Maven
        if: ${{ matrix.include.dependencyManager == 'maven' }}
        run: mvn -B package --file ${{ matrix.include.directory }}/{{ cookiecutter.project_slug }}/HelloWorldFunction/pom.xml
      - name: Build with Gradle
        if: ${{ matrix.include.dependencyManager == 'gradle' }}
        run: ./${{ matrix.include.directory }}/{{ cookiecutter.project_slug }}/HelloWorldFunction/gradlew build
